IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_AuditTrailDetails_AuditTrail')
BEGIN
	ALTER TABLE [dbo].[AuditTrailDetails] WITH CHECK ADD CONSTRAINT [FK_AuditTrailDetails_AuditTrail] FOREIGN KEY([QestUniqueParentID]) REFERENCES [dbo].[AuditTrail] ([QestUniqueID]) ON UPDATE NO ACTION ON DELETE CASCADE
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Defaults_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[Defaults] WITH CHECK ADD CONSTRAINT [FK_Defaults_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Defaults_qestObject')
BEGIN
	ALTER TABLE [dbo].[Defaults] WITH CHECK ADD CONSTRAINT [FK_Defaults_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_DocumentBulkDensityDirectMeasurement_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[DocumentBulkDensityDirectMeasurement] WITH CHECK ADD CONSTRAINT [FK_DocumentBulkDensityDirectMeasurement_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_DocumentIncrementalOedometerLoadStage_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[DocumentIncrementalOedometerLoadStage] WITH CHECK ADD CONSTRAINT [FK_DocumentIncrementalOedometerLoadStage_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_DocumentIncrementalOedometerLoadStageReading_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[DocumentIncrementalOedometerLoadStageReading] WITH CHECK ADD CONSTRAINT [FK_DocumentIncrementalOedometerLoadStageReading_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_DocumentTriaxial_TestAnalysisTriaxial')
BEGIN
	ALTER TABLE [dbo].[DocumentTriaxial] WITH CHECK ADD CONSTRAINT [FK_DocumentTriaxial_TestAnalysisTriaxial] FOREIGN KEY([TestAnalysisUUID]) REFERENCES [dbo].[TestAnalysisTriaxial] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_EquipmentTestMapping_qestReverseLookup_EquipmentQestUUID')
BEGIN
	ALTER TABLE [dbo].[EquipmentTestMapping] WITH CHECK ADD CONSTRAINT [FK_EquipmentTestMapping_qestReverseLookup_EquipmentQestUUID] FOREIGN KEY([EquipmentQestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_EquipmentTestMapping_qestReverseLookup_TestQestUUID')
BEGIN
	ALTER TABLE [dbo].[EquipmentTestMapping] WITH CHECK ADD CONSTRAINT [FK_EquipmentTestMapping_qestReverseLookup_TestQestUUID] FOREIGN KEY([TestQestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Laboratory_qestObject')
BEGIN
	ALTER TABLE [dbo].[Laboratory] WITH CHECK ADD CONSTRAINT [FK_Laboratory_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LaboratoryMapping_Laboratory')
BEGIN
	ALTER TABLE [dbo].[LaboratoryMapping] WITH CHECK ADD CONSTRAINT [FK_LaboratoryMapping_Laboratory] FOREIGN KEY([LocationUUID]) REFERENCES [dbo].[Laboratory] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListAssessmentTypes')
BEGIN
	ALTER TABLE [dbo].[ListAssessmentTypes] WITH CHECK ADD CONSTRAINT [FK_ListAssessmentTypes] FOREIGN KEY([LTPUUID]) REFERENCES [dbo].[LTP] ([LTPUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListClient_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListClient] WITH CHECK ADD CONSTRAINT [FK_ListClient_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListClient_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListClient] WITH CHECK ADD CONSTRAINT [FK_ListClient_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListConcreteTestGroup_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListConcreteTestGroup] WITH CHECK ADD CONSTRAINT [FK_ListConcreteTestGroup_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListConcreteTestGroup_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListConcreteTestGroup] WITH CHECK ADD CONSTRAINT [FK_ListConcreteTestGroup_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListContact_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListContact] WITH CHECK ADD CONSTRAINT [FK_ListContact_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListContact_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListContact] WITH CHECK ADD CONSTRAINT [FK_ListContact_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListContainerType_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListContainerType] WITH CHECK ADD CONSTRAINT [FK_ListContainerType_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListContainerType_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListContainerType] WITH CHECK ADD CONSTRAINT [FK_ListContainerType_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListMaterialCategory_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListMaterialCategory] WITH CHECK ADD CONSTRAINT [FK_ListMaterialCategory_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListMaterialCategory_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListMaterialCategory] WITH CHECK ADD CONSTRAINT [FK_ListMaterialCategory_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListProduct_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListProduct] WITH CHECK ADD CONSTRAINT [FK_ListProduct_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListProduct_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListProduct] WITH CHECK ADD CONSTRAINT [FK_ListProduct_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListProject_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListProject] WITH CHECK ADD CONSTRAINT [FK_ListProject_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListProject_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListProject] WITH CHECK ADD CONSTRAINT [FK_ListProject_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListProjectPurpose')
BEGIN
	ALTER TABLE [dbo].[ListProjectPurpose] WITH CHECK ADD CONSTRAINT [FK_ListProjectPurpose] FOREIGN KEY([LTPUUID]) REFERENCES [dbo].[LTP] ([LTPUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListSampleLocation_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListSampleLocation] WITH CHECK ADD CONSTRAINT [FK_ListSampleLocation_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListSampleLocation_LTP')
BEGIN
	ALTER TABLE [dbo].[ListSampleLocation] WITH CHECK ADD CONSTRAINT [FK_ListSampleLocation_LTP] FOREIGN KEY([LTPUUID]) REFERENCES [dbo].[LTP] ([LTPUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListSampleLocation_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListSampleLocation] WITH CHECK ADD CONSTRAINT [FK_ListSampleLocation_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListSamplingDevice_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListSamplingDevice] WITH CHECK ADD CONSTRAINT [FK_ListSamplingDevice_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListSamplingDevice_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListSamplingDevice] WITH CHECK ADD CONSTRAINT [FK_ListSamplingDevice_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListSteelSpliceType_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[ListSteelSpliceType] WITH CHECK ADD CONSTRAINT [FK_ListSteelSpliceType_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ListSteelSpliceType_qestObject')
BEGIN
	ALTER TABLE [dbo].[ListSteelSpliceType] WITH CHECK ADD CONSTRAINT [FK_ListSteelSpliceType_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LTP_PlannedTest_LTP')
BEGIN
	ALTER TABLE [dbo].[LTP_PlannedTest] WITH CHECK ADD CONSTRAINT [FK_LTP_PlannedTest_LTP] FOREIGN KEY([LTPUUID]) REFERENCES [dbo].[LTP] ([LTPUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LTP_PlannedTest_LTP_TriaxialSet')
BEGIN
	ALTER TABLE [dbo].[LTP_PlannedTest] WITH CHECK ADD CONSTRAINT [FK_LTP_PlannedTest_LTP_TriaxialSet] FOREIGN KEY([TriaxialSetUUID]) REFERENCES [dbo].[LTP_TriaxialSet] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LTP_PlannedTestConditions_LTP_PlannedTest')
BEGIN
	ALTER TABLE [dbo].[LTP_PlannedTestConditions] WITH CHECK ADD CONSTRAINT [FK_LTP_PlannedTestConditions_LTP_PlannedTest] FOREIGN KEY([PlannedTestUUID]) REFERENCES [dbo].[LTP_PlannedTest] ([PlannedTestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LTP_PlannedTestConditions_TestConditions')
BEGIN
	ALTER TABLE [dbo].[LTP_PlannedTestConditions] WITH CHECK ADD CONSTRAINT [FK_LTP_PlannedTestConditions_TestConditions] FOREIGN KEY([TestConditionUUID]) REFERENCES [dbo].[TestConditions] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LTP_PlannedTestStages_LTP_PlannedTest')
BEGIN
	ALTER TABLE [dbo].[LTP_PlannedTestStages] WITH CHECK ADD CONSTRAINT [FK_LTP_PlannedTestStages_LTP_PlannedTest] FOREIGN KEY([PlannedTestUUID]) REFERENCES [dbo].[LTP_PlannedTest] ([PlannedTestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LTP_PlannedTestStages_qestTestStages')
BEGIN
	ALTER TABLE [dbo].[LTP_PlannedTestStages] WITH CHECK ADD CONSTRAINT [FK_LTP_PlannedTestStages_qestTestStages] FOREIGN KEY([TestStageQestID]) REFERENCES [dbo].[qestTestStage] ([TestStageQestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LTP_TriaxialSet_LTP')
BEGIN
	ALTER TABLE [dbo].[LTP_TriaxialSet] WITH CHECK ADD CONSTRAINT [FK_LTP_TriaxialSet_LTP] FOREIGN KEY([LTPUUID]) REFERENCES [dbo].[LTP] ([LTPUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_People_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[People] WITH CHECK ADD CONSTRAINT [FK_People_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_People_qestObject')
BEGIN
	ALTER TABLE [dbo].[People] WITH CHECK ADD CONSTRAINT [FK_People_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestBusinessRule_qestEntity')
BEGIN
	ALTER TABLE [dbo].[qestBusinessRule] WITH CHECK ADD CONSTRAINT [FK_qestBusinessRule_qestEntity] FOREIGN KEY([QestEntityUUID]) REFERENCES [dbo].[qestEntity] ([QestEntityUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestBusinessRule_qestObject')
BEGIN
	ALTER TABLE [dbo].[qestBusinessRule] WITH CHECK ADD CONSTRAINT [FK_qestBusinessRule_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestObjects_qestObject')
BEGIN
	ALTER TABLE [dbo].[qestObjects] WITH CHECK ADD CONSTRAINT [FK_qestObjects_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestReportMapping_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[qestReportMapping] WITH CHECK ADD CONSTRAINT [FK_qestReportMapping_qestReverseLookup] FOREIGN KEY([TestQestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE CASCADE
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestReverseLookup_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[qestReverseLookup] WITH CHECK ADD CONSTRAINT [FK_qestReverseLookup_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestReverseLookup_qestObject')
BEGIN
	ALTER TABLE [dbo].[qestReverseLookup] WITH CHECK ADD CONSTRAINT [FK_qestReverseLookup_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestReverseLookup_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[qestReverseLookup] WITH CHECK ADD CONSTRAINT [FK_qestReverseLookup_qestReverseLookup] FOREIGN KEY([QestParentUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestReverseLookup_Samples')
BEGIN
	ALTER TABLE [dbo].[qestReverseLookup] WITH CHECK ADD CONSTRAINT [FK_qestReverseLookup_Samples] FOREIGN KEY([SampleArticleUUID]) REFERENCES [dbo].[Samples] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestTestStage_qestObject_TestQestID')
BEGIN
	ALTER TABLE [dbo].[qestTestStage] WITH CHECK ADD CONSTRAINT [FK_qestTestStage_qestObject_TestQestID] FOREIGN KEY([TestQestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestTestStage_qestObject_TestStageQestID')
BEGIN
	ALTER TABLE [dbo].[qestTestStage] WITH CHECK ADD CONSTRAINT [FK_qestTestStage_qestObject_TestStageQestID] FOREIGN KEY([TestStageQestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestView_qestEntity')
BEGIN
	ALTER TABLE [dbo].[qestView] WITH CHECK ADD CONSTRAINT [FK_qestView_qestEntity] FOREIGN KEY([QestEntityUUID]) REFERENCES [dbo].[qestEntity] ([QestEntityUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestWorkflow_qestEntity')
BEGIN
	ALTER TABLE [dbo].[qestWorkflow] WITH CHECK ADD CONSTRAINT [FK_qestWorkflow_qestEntity] FOREIGN KEY([OwnerQestEntityUUID]) REFERENCES [dbo].[qestEntity] ([QestEntityUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_qestWorkflowStage_qestWorkflow')
BEGIN
	ALTER TABLE [dbo].[qestWorkflowStage] WITH CHECK ADD CONSTRAINT [FK_qestWorkflowStage_qestWorkflow] FOREIGN KEY([WorkflowUUID]) REFERENCES [dbo].[qestWorkflow] ([WorkflowUUID]) ON UPDATE NO ACTION ON DELETE CASCADE
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Samples_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[Samples] WITH CHECK ADD CONSTRAINT [FK_Samples_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Samples_qestObject')
BEGIN
	ALTER TABLE [dbo].[Samples] WITH CHECK ADD CONSTRAINT [FK_Samples_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SessionConnections_Users')
BEGIN
	ALTER TABLE [dbo].[SessionConnections] WITH CHECK ADD CONSTRAINT [FK_SessionConnections_Users] FOREIGN KEY([UserUUID]) REFERENCES [dbo].[Users] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SessionLocks_SessionConnections')
BEGIN
	ALTER TABLE [dbo].[SessionLocks] WITH CHECK ADD CONSTRAINT [FK_SessionLocks_SessionConnections] FOREIGN KEY([SessionConnectionsUniqueID]) REFERENCES [dbo].[SessionConnections] ([UniqueID]) ON UPDATE NO ACTION ON DELETE CASCADE
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SpecificationRecords_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[SpecificationRecords] WITH CHECK ADD CONSTRAINT [FK_SpecificationRecords_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SpecificationRecords_qestObject')
BEGIN
	ALTER TABLE [dbo].[SpecificationRecords] WITH CHECK ADD CONSTRAINT [FK_SpecificationRecords_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SpecificationRecords_Specifications')
BEGIN
	ALTER TABLE [dbo].[SpecificationRecords] WITH CHECK ADD CONSTRAINT [FK_SpecificationRecords_Specifications] FOREIGN KEY([QestParentUUID]) REFERENCES [dbo].[Specifications] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Specifications_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[Specifications] WITH CHECK ADD CONSTRAINT [FK_Specifications_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Specifications_qestObject')
BEGIN
	ALTER TABLE [dbo].[Specifications] WITH CHECK ADD CONSTRAINT [FK_Specifications_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SuitabilityRuleConfiguration_SuitabilityRuleConfiguration')
BEGIN
	ALTER TABLE [dbo].[SuitabilityRuleConfiguration] WITH CHECK ADD CONSTRAINT [FK_SuitabilityRuleConfiguration_SuitabilityRuleConfiguration] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[SuitabilityRuleConfiguration] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SuitabilityRuleConfigurationTestConditions_SuitabilityRuleConfiguration')
BEGIN
	ALTER TABLE [dbo].[SuitabilityRuleConfigurationTestConditions] WITH CHECK ADD CONSTRAINT [FK_SuitabilityRuleConfigurationTestConditions_SuitabilityRuleConfiguration] FOREIGN KEY([SuitabilityRuleConfigurationUUID]) REFERENCES [dbo].[SuitabilityRuleConfiguration] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_SuitabilityRuleConfigurationTestConditions_TestConditions')
BEGIN
	ALTER TABLE [dbo].[SuitabilityRuleConfigurationTestConditions] WITH CHECK ADD CONSTRAINT [FK_SuitabilityRuleConfigurationTestConditions_TestConditions] FOREIGN KEY([TestConditionUUID]) REFERENCES [dbo].[TestConditions] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestAnalysisConsolidationCasagrande_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[TestAnalysisConsolidationCasagrande] WITH CHECK ADD CONSTRAINT [FK_TestAnalysisConsolidationCasagrande_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestAnalysisConsolidationTaylor_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[TestAnalysisConsolidationTaylor] WITH CHECK ADD CONSTRAINT [FK_TestAnalysisConsolidationTaylor_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestAnalysisOedPreconsolidationBecker_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[TestAnalysisOedPreconsolidationBecker] WITH CHECK ADD CONSTRAINT [FK_TestAnalysisOedPreconsolidationBecker_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestAnalysisOedPreconsolidationCasagrande_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[TestAnalysisOedPreconsolidationCasagrande] WITH CHECK ADD CONSTRAINT [FK_TestAnalysisOedPreconsolidationCasagrande_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestConditionField_TestConditions')
BEGIN
	ALTER TABLE [dbo].[TestConditionField] WITH CHECK ADD CONSTRAINT [FK_TestConditionField_TestConditions] FOREIGN KEY([TestConditionUUID]) REFERENCES [dbo].[TestConditions] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestStageData_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[TestStageData] WITH CHECK ADD CONSTRAINT [FK_TestStageData_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestStageData_qestObject')
BEGIN
	ALTER TABLE [dbo].[TestStageData] WITH CHECK ADD CONSTRAINT [FK_TestStageData_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestStageData_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[TestStageData] WITH CHECK ADD CONSTRAINT [FK_TestStageData_qestReverseLookup] FOREIGN KEY([QestParentUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE CASCADE
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_TestStageData_QestTestStage')
BEGIN
	ALTER TABLE [dbo].[TestStageData] WITH CHECK ADD CONSTRAINT [FK_TestStageData_QestTestStage] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestTestStage] ([TestStageQestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Users_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[Users] WITH CHECK ADD CONSTRAINT [FK_Users_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Users_People')
BEGIN
	ALTER TABLE [dbo].[Users] WITH CHECK ADD CONSTRAINT [FK_Users_People] FOREIGN KEY([PersonUUID]) REFERENCES [dbo].[People] ([QestUUID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Users_qestObject')
BEGIN
	ALTER TABLE [dbo].[Users] WITH CHECK ADD CONSTRAINT [FK_Users_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_WorkProgress_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[WorkProgress] WITH CHECK ADD CONSTRAINT [FK_WorkProgress_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_WorkProgress_qestObject')
BEGIN
	ALTER TABLE [dbo].[WorkProgress] WITH CHECK ADD CONSTRAINT [FK_WorkProgress_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_WorkProgress_qestReverseLookup')
BEGIN
	ALTER TABLE [dbo].[WorkProgress] WITH CHECK ADD CONSTRAINT [FK_WorkProgress_qestReverseLookup] FOREIGN KEY([QestUUID]) REFERENCES [dbo].[qestReverseLookup] ([QestUUID]) ON UPDATE NO ACTION ON DELETE CASCADE
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_WorkTemplates_LaboratoryMapping')
BEGIN
	ALTER TABLE [dbo].[WorkTemplates] WITH CHECK ADD CONSTRAINT [FK_WorkTemplates_LaboratoryMapping] FOREIGN KEY([QestOwnerLabNo]) REFERENCES [dbo].[LaboratoryMapping] ([LabNo]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_WorkTemplates_qestObject')
BEGIN
	ALTER TABLE [dbo].[WorkTemplates] WITH CHECK ADD CONSTRAINT [FK_WorkTemplates_qestObject] FOREIGN KEY([QestID]) REFERENCES [dbo].[qestObject] ([QestID]) ON UPDATE NO ACTION ON DELETE NO ACTION
END
GO

